language: generic
sudo: required

services:
  - docker

# Initial image
before_install:
  - docker build -t lifeasandythompson/react-test -f ./client/Dockerfile.dev ./client

# Tests scripts to run on the image
script:
  - docker run -e CI=true lifeasandythompson/react-test npm test 

# Add in configurations that will build production versions of our projects
after_success:
  - docker build -t n582346/multi-client ./client
  - docker build -t n582346/multi-nginx ./nginx
  - docker build -t n582346/multi-server ./server
  - docker build -t n582346/multi-worker ./worker
  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take images and push to docker hub
  - docker push n582346/multi-client
  - docker push n582346/multi-nginx
  - docker push n582346/multi-server
  - docker push n582346/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'MultiDocker-env-1'
  bucket_name: 'elasticbeanstalk-us-east-2-914005136749'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY