language: generic
sudo: required

services:
  - docker

# Initial image
before_install:
  - docker build -t lifeasandythompson/react-test -f ./client/Dockerfile.dev ./client

# Tests scripts to run on the image
script:
  - docker run -e CI=true lifeasandythompson/react-test npm test 

# Add in configurations that will build production versions of our projects
after_success:
  - docker build -t lifeasandythompson/multi-client ./client
  - docker build -t lifeasandythompson/multi-nginx ./nginx
  - docker build -t lifeasandythompson/multi-server ./server
  - docker build -t lifeasandythompson/multi-worker ./worker
  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take images and push to docker hub
  - docker push n582346/lifeasandythompson:multi-client
  - docker push n582346/lifeasandythompson:multi-nginx
  - docker push n582346/lifeasandythompson:multi-server
  - docker push n582346/lifeasandythompson:multi-worker