# Step 1: Use an existing docker image as a base
FROM node:14.14.0-alpine
WORKDIR "/app"

# Step 2: Install dependancies
COPY ./package.json ./
RUN npm install
COPY . .

# Step 3: Default command
CMD ["npm", "run", "dev"]